security:
    encoders:
        App\Entity\WebUser:
            algorithm: argon2i

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\WebUser
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #main:
        #    two_factor:
        #        auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
        #        check_path: 2fa_login_check  # The route name you have used in the routes.yaml
        login:
            pattern:  ^/auth
            stateless: true
            anonymous: true
            json_login:
                check_path: /auth/tokens
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    # The path patterns shown here have to be updated according to your routes, if you're going with something custom
    access_control:
        - { path: ^/auth/tokens, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        # This makes the logout route available during two-factor authentication, allows the user to cancel
        #- { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # This ensures that the form can only be accessed when two-factor authentication is in progress
        #- { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }